// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_ISJg390Za0l2_lZ0oSonXzGja7hbR0',
    appId: '1:111761112037:web:8b2e46421a44b4b4010d0c',
    messagingSenderId: '111761112037',
    projectId: 'runcast-67',
    authDomain: 'runcast-67.firebaseapp.com',
    storageBucket: 'runcast-67.firebasestorage.app',
    measurementId: 'G-S7TB4R0Y7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-v0K-idYlshmN0wnAffMA-ASMed0cAos',
    appId: '1:111761112037:android:4a93ae6c895dfcef010d0c',
    messagingSenderId: '111761112037',
    projectId: 'runcast-67',
    storageBucket: 'runcast-67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxNOKoaSzXdtdxyjMMXfeY0jD95REglQ',
    appId: '1:111761112037:ios:f2d82fafb711728e010d0c',
    messagingSenderId: '111761112037',
    projectId: 'runcast-67',
    storageBucket: 'runcast-67.firebasestorage.app',
    iosBundleId: 'com.example.runcast',
  );
}
